// <auto-generated />
using System;
using CDM.Match;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CDM.Odds.Migrations
{
    [DbContext(typeof(OddDbContext))]
    [Migration("20260120102124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CDM.Odds.Models.OddsEntity", b =>
                {
                    b.Property<int>("OddId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OddId"));

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("OddCreated")
                        .HasColumnType("date");

                    b.Property<float>("OddDraw")
                        .HasColumnType("real");

                    b.Property<float>("OddFirstTeamWinning")
                        .HasColumnType("real");

                    b.Property<float>("OddSecondTeamWinning")
                        .HasColumnType("real");

                    b.Property<DateOnly>("OddUpdated")
                        .HasColumnType("date");

                    b.HasKey("OddId");

                    b.ToTable("Odds");
                });
#pragma warning restore 612, 618
        }
    }
}
